/*
* generated by Xtext
*/
package br.gov.frameworkdemoiselle.behave.plugin.eclipse.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import br.gov.frameworkdemoiselle.behave.plugin.eclipse.dsl.services.StoryDslGrammarAccess;

public class StoryDslParser extends AbstractContentAssistParser {
	
	@Inject
	private StoryDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected br.gov.frameworkdemoiselle.behave.plugin.eclipse.dsl.ui.contentassist.antlr.internal.InternalStoryDslParser createParser() {
		br.gov.frameworkdemoiselle.behave.plugin.eclipse.dsl.ui.contentassist.antlr.internal.InternalStoryDslParser result = new br.gov.frameworkdemoiselle.behave.plugin.eclipse.dsl.ui.contentassist.antlr.internal.InternalStoryDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSentencaQualiteAccess().getAlternatives(), "rule__SentencaQualite__Alternatives");
					put(grammarAccess.getListaMetasAccess().getAlternatives_0(), "rule__ListaMetas__Alternatives_0");
					put(grammarAccess.getExecutarCenarioAccess().getAlternatives_0(), "rule__ExecutarCenario__Alternatives_0");
					put(grammarAccess.getListaItensAccess().getAlternatives_0_0_0(), "rule__ListaItens__Alternatives_0_0_0");
					put(grammarAccess.getListaItensAccess().getAlternatives_0_1(), "rule__ListaItens__Alternatives_0_1");
					put(grammarAccess.getIDENTIFICADOR_GERALAccess().getAlternatives_0(), "rule__IDENTIFICADOR_GERAL__Alternatives_0");
					put(grammarAccess.getIDENTIFICADOR_GERALAccess().getAlternatives_1_1(), "rule__IDENTIFICADOR_GERAL__Alternatives_1_1");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getUsuarioMetaRazaoAccess().getGroup(), "rule__UsuarioMetaRazao__Group__0");
					put(grammarAccess.getFuncionalidadeAccess().getGroup(), "rule__Funcionalidade__Group__0");
					put(grammarAccess.getCenarioAccess().getGroup(), "rule__Cenario__Group__0");
					put(grammarAccess.getMetaAccess().getGroup(), "rule__Meta__Group__0");
					put(grammarAccess.getListaMetasAccess().getGroup(), "rule__ListaMetas__Group__0");
					put(grammarAccess.getExecutarCenarioAccess().getGroup(), "rule__ExecutarCenario__Group__0");
					put(grammarAccess.getListaItensAccess().getGroup(), "rule__ListaItens__Group__0");
					put(grammarAccess.getListaItensAccess().getGroup_0(), "rule__ListaItens__Group_0__0");
					put(grammarAccess.getListaItensAccess().getGroup_0_0(), "rule__ListaItens__Group_0_0__0");
					put(grammarAccess.getIDENTIFICADOR_GERALAccess().getGroup(), "rule__IDENTIFICADOR_GERAL__Group__0");
					put(grammarAccess.getIDENTIFICADOR_GERALAccess().getGroup_1(), "rule__IDENTIFICADOR_GERAL__Group_1__0");
					put(grammarAccess.getModelAccess().getFuncionalidadeAssignment_1(), "rule__Model__FuncionalidadeAssignment_1");
					put(grammarAccess.getModelAccess().getUsuarioMetaRazaoAssignment_3(), "rule__Model__UsuarioMetaRazaoAssignment_3");
					put(grammarAccess.getModelAccess().getCenariosAssignment_4(), "rule__Model__CenariosAssignment_4");
					put(grammarAccess.getUsuarioMetaRazaoAccess().getNome_do_atorAssignment_1(), "rule__UsuarioMetaRazao__Nome_do_atorAssignment_1");
					put(grammarAccess.getUsuarioMetaRazaoAccess().getMeta_a_ser_alcancadaAssignment_4(), "rule__UsuarioMetaRazao__Meta_a_ser_alcancadaAssignment_4");
					put(grammarAccess.getUsuarioMetaRazaoAccess().getRazao_para_alcancar_metaAssignment_7(), "rule__UsuarioMetaRazao__Razao_para_alcancar_metaAssignment_7");
					put(grammarAccess.getFuncionalidadeAccess().getNome_funcionadadeAssignment_1(), "rule__Funcionalidade__Nome_funcionadadeAssignment_1");
					put(grammarAccess.getCenarioAccess().getXerAssignment_2(), "rule__Cenario__XerAssignment_2");
					put(grammarAccess.getCenarioAccess().getSentencas_qualiteAssignment_3(), "rule__Cenario__Sentencas_qualiteAssignment_3");
					put(grammarAccess.getIdentificadorCenarioAccess().getNameAssignment(), "rule__IdentificadorCenario__NameAssignment");
					put(grammarAccess.getMetaAccess().getXAssignment_0(), "rule__Meta__XAssignment_0");
					put(grammarAccess.getMetaAccess().getLista_metasAssignment_2(), "rule__Meta__Lista_metasAssignment_2");
					put(grammarAccess.getExecutarCenarioAccess().getCenario_executar_refAssignment_1(), "rule__ExecutarCenario__Cenario_executar_refAssignment_1");
					put(grammarAccess.getListaItensAccess().getItemAssignment_0_0_1(), "rule__ListaItens__ItemAssignment_0_0_1");
					put(grammarAccess.getNOME_DO_ATORAccess().getNome_do_atorAssignment(), "rule__NOME_DO_ATOR__Nome_do_atorAssignment");
					put(grammarAccess.getMETA_A_SER_ALCANCADAAccess().getMeta_a_ser_alcancadaAssignment(), "rule__META_A_SER_ALCANCADA__Meta_a_ser_alcancadaAssignment");
					put(grammarAccess.getRAZAO_PARA_ALCANCAR_A_METAAccess().getRazao_para_alcancar_a_metaAssignment(), "rule__RAZAO_PARA_ALCANCAR_A_META__Razao_para_alcancar_a_metaAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			br.gov.frameworkdemoiselle.behave.plugin.eclipse.dsl.ui.contentassist.antlr.internal.InternalStoryDslParser typedParser = (br.gov.frameworkdemoiselle.behave.plugin.eclipse.dsl.ui.contentassist.antlr.internal.InternalStoryDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public StoryDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StoryDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
