//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.13 at 12:00:05 PM BRT 
//


package com.ibm.rqm.xml.bind.tasks;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.rqm.xml.bind.tasks package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Relativepath_QNAME = new QName("http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", "relativepath");
    private final static QName _Managedbyadapter_QNAME = new QName("http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", "managedbyadapter");
    private final static QName _SelectedAdapterId_QNAME = new QName("http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", "selectedAdapterId");
    private final static QName _Fullpath_QNAME = new QName("http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", "fullpath");
    private final static QName _Taken_QNAME = new QName("http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", "taken");
    private final static QName _Progress_QNAME = new QName("http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", "progress");
    private final static QName _Shareprefix_QNAME = new QName("http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", "shareprefix");
    private final static QName _Type_QNAME = new QName("http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", "type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.rqm.xml.bind.tasks
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateURL }
     * 
     */
    public UpdateURL createUpdateURL() {
        return new UpdateURL();
    }

    /**
     * Create an instance of {@link Properties.Property }
     * 
     */
    public Properties.Property createPropertiesProperty() {
        return new Properties.Property();
    }

    /**
     * Create an instance of {@link Ewi }
     * 
     */
    public Ewi createEwi() {
        return new Ewi();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link SuiteLogURL }
     * 
     */
    public SuiteLogURL createSuiteLogURL() {
        return new SuiteLogURL();
    }

    /**
     * Create an instance of {@link RecordingURL }
     * 
     */
    public RecordingURL createRecordingURL() {
        return new RecordingURL();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link ResultURL }
     * 
     */
    public ResultURL createResultURL() {
        return new ResultURL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", name = "relativepath")
    public JAXBElement<String> createRelativepath(String value) {
        return new JAXBElement<String>(_Relativepath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", name = "managedbyadapter")
    public JAXBElement<Boolean> createManagedbyadapter(Boolean value) {
        return new JAXBElement<Boolean>(_Managedbyadapter_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", name = "selectedAdapterId")
    public JAXBElement<String> createSelectedAdapterId(String value) {
        return new JAXBElement<String>(_SelectedAdapterId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", name = "fullpath")
    public JAXBElement<String> createFullpath(String value) {
        return new JAXBElement<String>(_Fullpath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", name = "taken")
    public JAXBElement<Boolean> createTaken(Boolean value) {
        return new JAXBElement<Boolean>(_Taken_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", name = "progress")
    public JAXBElement<Integer> createProgress(Integer value) {
        return new JAXBElement<Integer>(_Progress_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", name = "shareprefix")
    public JAXBElement<String> createShareprefix(String value) {
        return new JAXBElement<String>(_Shareprefix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

}
