/*
 * generated by Xtext
 */
package br.gov.frameworkdemoiselle.behave.plugin.eclipse.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import br.gov.frameworkdemoiselle.behave.plugin.eclipse.dsl.ui.internal.StoryDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StoryDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StoryDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StoryDslActivator.getInstance().getInjector(StoryDslActivator.BR_GOV_FRAMEWORKDEMOISELLE_BEHAVE_PLUGIN_ECLIPSE_DSL_STORYDSL);
	}
	
}
