//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.13 at 12:00:05 PM BRT 
//


package com.ibm.rqm.xml.rdf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.ibm.rqm.xml.bind.oslc_qm.TestCase;
import com.ibm.rqm.xml.bind.oslc_qm.TestExecutionRecord;
import com.ibm.rqm.xml.bind.oslc_qm.TestPlan;
import com.ibm.rqm.xml.bind.oslc_qm.TestScript;


/**
 * <p>Java class for typedNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typedNodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.w3.org/1999/02/22-rdf-syntax-ns#}propertyElt"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.w3.org/1999/02/22-rdf-syntax-ns#}idAboutAttrOpt"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typedNodeType", propOrder = {
    "propertyElt"
})
@XmlSeeAlso({
    TestPlan.class,
    TestCase.class,
    TestScript.class,
    TestExecutionRecord.class
})
public class TypedNodeType {

    @XmlElementRef(name = "propertyElt", namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#", type = JAXBElement.class)
    protected List<JAXBElement<PropertyEltType>> propertyElt;
    @XmlAttribute(namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String about;

    /**
     * Gets the value of the propertyElt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyElt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyElt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PropertyEltType }{@code >}
     * {@link JAXBElement }{@code <}{@link PropertyEltType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<PropertyEltType>> getPropertyElt() {
        if (propertyElt == null) {
            propertyElt = new ArrayList<JAXBElement<PropertyEltType>>();
        }
        return this.propertyElt;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

}
