//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.13 at 12:00:05 PM BRT 
//


package com.ibm.rqm.xml.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://jazz.net/xmlns/alm/qm/v0.1/}reportableArtifact">
 *       &lt;sequence>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}snapshot" minOccurs="0"/>
 *         &lt;element name="webId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}title"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}description" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}creationDate"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}updated"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}state"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}creator"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}owner"/>
 *         &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}variables"/>
 *         &lt;element name="includeBuiltInVars" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}approvals" minOccurs="0"/>
 *         &lt;element name="steps">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}step" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datapool" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}customAttributes" minOccurs="0"/>
 *         &lt;element name="category" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="term" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="task" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://purl.org/dc/terms/}type" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}recordselectioncriteria" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="remote">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="shareprefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="relativepath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="fullpath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="manageadapter" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="adapterid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="labresource" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}inputParameter" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}markerAny"/>
 *                   &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}copiedFrom" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}copiedRoot" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}esignatures" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "snapshot",
    "webId",
    "title",
    "description",
    "creationDate",
    "updated",
    "state",
    "creator",
    "owner",
    "locked",
    "variables",
    "includeBuiltInVars",
    "approvals",
    "steps",
    "datapool",
    "customAttributes",
    "category",
    "task",
    "type",
    "recordselectioncriteria",
    "remote",
    "copiedFrom",
    "copiedRoot",
    "esignatures"
})
@XmlRootElement(name = "executionscript")
public class Executionscript
    extends ReportableArtifact
{

    protected Snapshot snapshot;
    protected Integer webId;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected String title;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/")
    protected String description;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updated;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    protected State state;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected Creator creator;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    protected Owner owner;
    protected Boolean locked;
    @XmlElement(required = true)
    protected Variables variables;
    protected Boolean includeBuiltInVars;
    protected Approvals approvals;
    @XmlElement(required = true)
    protected Executionscript.Steps steps;
    protected Executionscript.Datapool datapool;
    protected CustomAttributes customAttributes;
    protected List<Executionscript.Category> category;
    protected List<Executionscript.Task> task;
    @XmlElement(namespace = "http://purl.org/dc/terms/")
    protected String type;
    protected List<Recordselectioncriteria> recordselectioncriteria;
    @XmlElement(required = true)
    protected Executionscript.Remote remote;
    protected CopiedFrom copiedFrom;
    protected CopiedRoot copiedRoot;
    protected Esignatures esignatures;

    /**
     * [READ-ONLY] Snapshot metadata associated with the snapshot of the execution script.  Note, supported only for execution script snapshots.
     * 
     * @return
     *     possible object is
     *     {@link Snapshot }
     *     
     */
    public Snapshot getSnapshot() {
        return snapshot;
    }

    /**
     * Sets the value of the snapshot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Snapshot }
     *     
     */
    public void setSnapshot(Snapshot value) {
        this.snapshot = value;
    }

    /**
     * Gets the value of the webId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWebId() {
        return webId;
    }

    /**
     * Sets the value of the webId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWebId(Integer value) {
        this.webId = value;
    }

    /**
     * A name given to the execution script.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * An account of the executionscript.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * [READ-ONLY] The last modification date of a resource.  Format is XML dateTime.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdated(XMLGregorianCalendar value) {
        this.updated = value;
    }

    /**
     * An ID or name of the current state of the execution script.
     * 
     * @return
     *     possible object is
     *     {@link State }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link State }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * [IMMUTABLE] The contributor that created the execution script.
     * 
     * @return
     *     possible object is
     *     {@link Creator }
     *     
     */
    public Creator getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Creator }
     *     
     */
    public void setCreator(Creator value) {
        this.creator = value;
    }

    /**
     * The contributor that owns the execution script.
     * 
     * @return
     *     possible object is
     *     {@link Owner }
     *     
     */
    public Owner getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Owner }
     *     
     */
    public void setOwner(Owner value) {
        this.owner = value;
    }

    /**
     * Gets the value of the locked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLocked() {
        return locked;
    }

    /**
     * Sets the value of the locked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocked(Boolean value) {
        this.locked = value;
    }

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link Variables }
     *     
     */
    public Variables getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variables }
     *     
     */
    public void setVariables(Variables value) {
        this.variables = value;
    }

    /**
     * Gets the value of the includeBuiltInVars property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeBuiltInVars() {
        return includeBuiltInVars;
    }

    /**
     * Sets the value of the includeBuiltInVars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeBuiltInVars(Boolean value) {
        this.includeBuiltInVars = value;
    }

    /**
     * A collection of approvals that are associated with the execution script.
     * 
     * @return
     *     possible object is
     *     {@link Approvals }
     *     
     */
    public Approvals getApprovals() {
        return approvals;
    }

    /**
     * Sets the value of the approvals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Approvals }
     *     
     */
    public void setApprovals(Approvals value) {
        this.approvals = value;
    }

    /**
     * Gets the value of the steps property.
     * 
     * @return
     *     possible object is
     *     {@link Executionscript.Steps }
     *     
     */
    public Executionscript.Steps getSteps() {
        return steps;
    }

    /**
     * Sets the value of the steps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Executionscript.Steps }
     *     
     */
    public void setSteps(Executionscript.Steps value) {
        this.steps = value;
    }

    /**
     * Gets the value of the datapool property.
     * 
     * @return
     *     possible object is
     *     {@link Executionscript.Datapool }
     *     
     */
    public Executionscript.Datapool getDatapool() {
        return datapool;
    }

    /**
     * Sets the value of the datapool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Executionscript.Datapool }
     *     
     */
    public void setDatapool(Executionscript.Datapool value) {
        this.datapool = value;
    }

    /**
     * User defined custom attribute name/value data on this artifact.
     * 
     * @return
     *     possible object is
     *     {@link CustomAttributes }
     *     
     */
    public CustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomAttributes }
     *     
     */
    public void setCustomAttributes(CustomAttributes value) {
        this.customAttributes = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Executionscript.Category }
     * 
     * 
     */
    public List<Executionscript.Category> getCategory() {
        if (category == null) {
            category = new ArrayList<Executionscript.Category>();
        }
        return this.category;
    }

    /**
     * Gets the value of the task property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the task property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTask().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Executionscript.Task }
     * 
     * 
     */
    public List<Executionscript.Task> getTask() {
        if (task == null) {
            task = new ArrayList<Executionscript.Task>();
        }
        return this.task;
    }

    /**
     * The value is Manual, or the type of adapter that runs the script RFT, RPT, etc. The adapter provides this identifier in its plugin metadata. Some possible values are: Manual, RQM-KEY-APPSCAN-APTR-TYPE-NAME, RQM-KEY-CMD-APTR-TYPE-NAME, RQM-KEY-RFT-APTR-TYPE-NAME, RQM-KEY-ROBOT-APTR-TYPE-NAME, and RQM-KEY-RPT-APTR-TYPE-NAME
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the recordselectioncriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordselectioncriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordselectioncriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Recordselectioncriteria }
     * 
     * 
     */
    public List<Recordselectioncriteria> getRecordselectioncriteria() {
        if (recordselectioncriteria == null) {
            recordselectioncriteria = new ArrayList<Recordselectioncriteria>();
        }
        return this.recordselectioncriteria;
    }

    /**
     * Gets the value of the remote property.
     * 
     * @return
     *     possible object is
     *     {@link Executionscript.Remote }
     *     
     */
    public Executionscript.Remote getRemote() {
        return remote;
    }

    /**
     * Sets the value of the remote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Executionscript.Remote }
     *     
     */
    public void setRemote(Executionscript.Remote value) {
        this.remote = value;
    }

    /**
     * [READ-ONLY] Link to the execution script from which this execution script was copied.
     * 
     * @return
     *     possible object is
     *     {@link CopiedFrom }
     *     
     */
    public CopiedFrom getCopiedFrom() {
        return copiedFrom;
    }

    /**
     * Sets the value of the copiedFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link CopiedFrom }
     *     
     */
    public void setCopiedFrom(CopiedFrom value) {
        this.copiedFrom = value;
    }

    /**
     * [READ-ONLY] Link to the execution script from which this execution script was ultimately derived.
     * 
     * @return
     *     possible object is
     *     {@link CopiedRoot }
     *     
     */
    public CopiedRoot getCopiedRoot() {
        return copiedRoot;
    }

    /**
     * Sets the value of the copiedRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link CopiedRoot }
     *     
     */
    public void setCopiedRoot(CopiedRoot value) {
        this.copiedRoot = value;
    }

    /**
     * Gets the value of the esignatures property.
     * 
     * @return
     *     possible object is
     *     {@link Esignatures }
     *     
     */
    public Esignatures getEsignatures() {
        return esignatures;
    }

    /**
     * Sets the value of the esignatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Esignatures }
     *     
     */
    public void setEsignatures(Esignatures value) {
        this.esignatures = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="term" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Category {

        @XmlAttribute
        protected String term;
        @XmlAttribute
        protected String value;

        /**
         * Gets the value of the term property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTerm() {
            return term;
        }

        /**
         * Sets the value of the term property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTerm(String value) {
            this.term = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Datapool {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="shareprefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="relativepath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="fullpath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="manageadapter" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="adapterid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="labresource" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}inputParameter" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}markerAny"/>
     *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shareprefix",
        "relativepath",
        "fullpath",
        "manageadapter",
        "adapterid",
        "labresource",
        "inputParameter",
        "markerAny",
        "any"
    })
    public static class Remote {

        protected String shareprefix;
        protected String relativepath;
        protected String fullpath;
        protected Boolean manageadapter;
        protected String adapterid;
        protected Executionscript.Remote.Labresource labresource;
        protected List<InputParameter> inputParameter;
        @XmlElement(required = true)
        protected String markerAny;
        @XmlAnyElement
        protected List<Element> any;

        /**
         * Gets the value of the shareprefix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShareprefix() {
            return shareprefix;
        }

        /**
         * Sets the value of the shareprefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShareprefix(String value) {
            this.shareprefix = value;
        }

        /**
         * Gets the value of the relativepath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRelativepath() {
            return relativepath;
        }

        /**
         * Sets the value of the relativepath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRelativepath(String value) {
            this.relativepath = value;
        }

        /**
         * Gets the value of the fullpath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullpath() {
            return fullpath;
        }

        /**
         * Sets the value of the fullpath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullpath(String value) {
            this.fullpath = value;
        }

        /**
         * Gets the value of the manageadapter property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isManageadapter() {
            return manageadapter;
        }

        /**
         * Sets the value of the manageadapter property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setManageadapter(Boolean value) {
            this.manageadapter = value;
        }

        /**
         * Gets the value of the adapterid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdapterid() {
            return adapterid;
        }

        /**
         * Sets the value of the adapterid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdapterid(String value) {
            this.adapterid = value;
        }

        /**
         * Gets the value of the labresource property.
         * 
         * @return
         *     possible object is
         *     {@link Executionscript.Remote.Labresource }
         *     
         */
        public Executionscript.Remote.Labresource getLabresource() {
            return labresource;
        }

        /**
         * Sets the value of the labresource property.
         * 
         * @param value
         *     allowed object is
         *     {@link Executionscript.Remote.Labresource }
         *     
         */
        public void setLabresource(Executionscript.Remote.Labresource value) {
            this.labresource = value;
        }

        /**
         * Gets the value of the inputParameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the inputParameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInputParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InputParameter }
         * 
         * 
         */
        public List<InputParameter> getInputParameter() {
            if (inputParameter == null) {
                inputParameter = new ArrayList<InputParameter>();
            }
            return this.inputParameter;
        }

        /**
         * [READ-ONLY] A empty marker.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMarkerAny() {
            return markerAny;
        }

        /**
         * Sets the value of the markerAny property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMarkerAny(String value) {
            this.markerAny = value;
        }

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * 
         * 
         */
        public List<Element> getAny() {
            if (any == null) {
                any = new ArrayList<Element>();
            }
            return this.any;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Labresource {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "anyURI")
            protected String href;

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}step" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "step"
    })
    public static class Steps {

        @XmlElement(required = true)
        protected List<ExecutionScriptStep> step;

        /**
         * A step embedded in the execution script.Gets the value of the step property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the step property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStep().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExecutionScriptStep }
         * 
         * 
         */
        public List<ExecutionScriptStep> getStep() {
            if (step == null) {
                step = new ArrayList<ExecutionScriptStep>();
            }
            return this.step;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Task {

        @XmlAttribute
        protected String rel;
        @XmlAttribute
        protected String summary;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;

        /**
         * Gets the value of the rel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRel() {
            return rel;
        }

        /**
         * Sets the value of the rel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRel(String value) {
            this.rel = value;
        }

        /**
         * Gets the value of the summary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSummary() {
            return summary;
        }

        /**
         * Sets the value of the summary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSummary(String value) {
            this.summary = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

    }

}
