//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.13 at 12:00:05 PM BRT 
//


package com.ibm.rqm.xml.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.ibm.rqm.xml.bind.adapter.Instruction;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/qmadapter/v0.1}workavailable" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/qmadapter/v0.1}instruction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "workavailable",
    "instruction"
})
@XmlRootElement(name = "instructions")
public class Instructions {

    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/v0.1")
    protected Boolean workavailable;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/v0.1")
    protected List<Instruction> instruction;

    /**
     * [READ-ONLY] Indicates if there is something for the adapter to do.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWorkavailable() {
        return workavailable;
    }

    /**
     * Sets the value of the workavailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWorkavailable(Boolean value) {
        this.workavailable = value;
    }

    /**
     * [READ-ONLY] An instruction for the adapter.Gets the value of the instruction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instruction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstruction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Instruction }
     * 
     * 
     */
    public List<Instruction> getInstruction() {
        if (instruction == null) {
            instruction = new ArrayList<Instruction>();
        }
        return this.instruction;
    }

}
