//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.13 at 12:00:05 PM BRT 
//


package com.ibm.rqm.xml.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://jazz.net/xmlns/alm/qm/v0.1/}reportableArtifact">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}description"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="type">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="memory" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *             &lt;element name="ipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="primaryMacAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="administrativeStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="operationalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="hostname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="fullyQualifiedDomainName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="osType">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *             &lt;element name="osLocale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="osKernelWidth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="cpuSpeed" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *             &lt;element name="cpuArchitecture" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="cpuArchitectureWidth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="cpuManufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="cpuType">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *             &lt;element name="diskspace" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *             &lt;element name="imageType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="vmFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="vmToolUsed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="software">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element name="softwareInstall" maxOccurs="unbounded" minOccurs="0">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                               &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                               &lt;attribute name="installLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                               &lt;attribute name="executable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                     &lt;/sequence>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *             &lt;element name="resourcegroup" minOccurs="0">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                     &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;element name="tdm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="property" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "description",
    "type",
    "name",
    "memory",
    "ipAddress",
    "systemId",
    "primaryMacAddress",
    "administrativeStatus",
    "operationalStatus",
    "hostname",
    "fullyQualifiedDomainName",
    "osType",
    "osLocale",
    "osKernelWidth",
    "cpuSpeed",
    "cpuArchitecture",
    "cpuArchitectureWidth",
    "cpuManufacturer",
    "cpuType",
    "diskspace",
    "imageType",
    "vmFile",
    "vmToolUsed",
    "software",
    "resourcegroup",
    "tdm",
    "property"
})
@XmlRootElement(name = "labresource")
public class Labresource
    extends ReportableArtifact
{

    @XmlElement(required = true)
    protected String title;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected String description;
    protected Labresource.Type type;
    protected String name;
    protected Integer memory;
    protected String ipAddress;
    protected String systemId;
    protected String primaryMacAddress;
    protected String administrativeStatus;
    protected String operationalStatus;
    protected String hostname;
    protected String fullyQualifiedDomainName;
    protected Labresource.OsType osType;
    protected String osLocale;
    protected String osKernelWidth;
    protected Integer cpuSpeed;
    protected String cpuArchitecture;
    protected String cpuArchitectureWidth;
    protected String cpuManufacturer;
    protected Labresource.CpuType cpuType;
    protected Integer diskspace;
    protected String imageType;
    protected String vmFile;
    protected String vmToolUsed;
    protected Labresource.Software software;
    protected Labresource.Resourcegroup resourcegroup;
    protected String tdm;
    protected List<Labresource.Property> property;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * A summary description of the lab resource.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Labresource.Type }
     *     
     */
    public Labresource.Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Labresource.Type }
     *     
     */
    public void setType(Labresource.Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the memory property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMemory(Integer value) {
        this.memory = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the primaryMacAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryMacAddress() {
        return primaryMacAddress;
    }

    /**
     * Sets the value of the primaryMacAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryMacAddress(String value) {
        this.primaryMacAddress = value;
    }

    /**
     * Gets the value of the administrativeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdministrativeStatus() {
        return administrativeStatus;
    }

    /**
     * Sets the value of the administrativeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdministrativeStatus(String value) {
        this.administrativeStatus = value;
    }

    /**
     * Gets the value of the operationalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalStatus() {
        return operationalStatus;
    }

    /**
     * Sets the value of the operationalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalStatus(String value) {
        this.operationalStatus = value;
    }

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostname(String value) {
        this.hostname = value;
    }

    /**
     * Gets the value of the fullyQualifiedDomainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullyQualifiedDomainName() {
        return fullyQualifiedDomainName;
    }

    /**
     * Sets the value of the fullyQualifiedDomainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullyQualifiedDomainName(String value) {
        this.fullyQualifiedDomainName = value;
    }

    /**
     * Gets the value of the osType property.
     * 
     * @return
     *     possible object is
     *     {@link Labresource.OsType }
     *     
     */
    public Labresource.OsType getOsType() {
        return osType;
    }

    /**
     * Sets the value of the osType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Labresource.OsType }
     *     
     */
    public void setOsType(Labresource.OsType value) {
        this.osType = value;
    }

    /**
     * Gets the value of the osLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsLocale() {
        return osLocale;
    }

    /**
     * Sets the value of the osLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsLocale(String value) {
        this.osLocale = value;
    }

    /**
     * Gets the value of the osKernelWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsKernelWidth() {
        return osKernelWidth;
    }

    /**
     * Sets the value of the osKernelWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsKernelWidth(String value) {
        this.osKernelWidth = value;
    }

    /**
     * Gets the value of the cpuSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCpuSpeed() {
        return cpuSpeed;
    }

    /**
     * Sets the value of the cpuSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCpuSpeed(Integer value) {
        this.cpuSpeed = value;
    }

    /**
     * Gets the value of the cpuArchitecture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpuArchitecture() {
        return cpuArchitecture;
    }

    /**
     * Sets the value of the cpuArchitecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpuArchitecture(String value) {
        this.cpuArchitecture = value;
    }

    /**
     * Gets the value of the cpuArchitectureWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpuArchitectureWidth() {
        return cpuArchitectureWidth;
    }

    /**
     * Sets the value of the cpuArchitectureWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpuArchitectureWidth(String value) {
        this.cpuArchitectureWidth = value;
    }

    /**
     * Gets the value of the cpuManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpuManufacturer() {
        return cpuManufacturer;
    }

    /**
     * Sets the value of the cpuManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpuManufacturer(String value) {
        this.cpuManufacturer = value;
    }

    /**
     * Gets the value of the cpuType property.
     * 
     * @return
     *     possible object is
     *     {@link Labresource.CpuType }
     *     
     */
    public Labresource.CpuType getCpuType() {
        return cpuType;
    }

    /**
     * Sets the value of the cpuType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Labresource.CpuType }
     *     
     */
    public void setCpuType(Labresource.CpuType value) {
        this.cpuType = value;
    }

    /**
     * Gets the value of the diskspace property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDiskspace() {
        return diskspace;
    }

    /**
     * Sets the value of the diskspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDiskspace(Integer value) {
        this.diskspace = value;
    }

    /**
     * Gets the value of the imageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * Sets the value of the imageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageType(String value) {
        this.imageType = value;
    }

    /**
     * Gets the value of the vmFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVmFile() {
        return vmFile;
    }

    /**
     * Sets the value of the vmFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVmFile(String value) {
        this.vmFile = value;
    }

    /**
     * Gets the value of the vmToolUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVmToolUsed() {
        return vmToolUsed;
    }

    /**
     * Sets the value of the vmToolUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVmToolUsed(String value) {
        this.vmToolUsed = value;
    }

    /**
     * Gets the value of the software property.
     * 
     * @return
     *     possible object is
     *     {@link Labresource.Software }
     *     
     */
    public Labresource.Software getSoftware() {
        return software;
    }

    /**
     * Sets the value of the software property.
     * 
     * @param value
     *     allowed object is
     *     {@link Labresource.Software }
     *     
     */
    public void setSoftware(Labresource.Software value) {
        this.software = value;
    }

    /**
     * Gets the value of the resourcegroup property.
     * 
     * @return
     *     possible object is
     *     {@link Labresource.Resourcegroup }
     *     
     */
    public Labresource.Resourcegroup getResourcegroup() {
        return resourcegroup;
    }

    /**
     * Sets the value of the resourcegroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Labresource.Resourcegroup }
     *     
     */
    public void setResourcegroup(Labresource.Resourcegroup value) {
        this.resourcegroup = value;
    }

    /**
     * Gets the value of the tdm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdm() {
        return tdm;
    }

    /**
     * Sets the value of the tdm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdm(String value) {
        this.tdm = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Labresource.Property }
     * 
     * 
     */
    public List<Labresource.Property> getProperty() {
        if (property == null) {
            property = new ArrayList<Labresource.Property>();
        }
        return this.property;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class CpuType {

        @XmlValue
        protected String content;
        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String href;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class OsType {

        @XmlValue
        protected String content;
        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String href;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Property {

        @XmlAttribute
        protected String value;
        @XmlAttribute(required = true)
        protected String name;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Resourcegroup {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the resource group.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="softwareInstall" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="installLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="executable" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "softwareInstall"
    })
    public static class Software {

        protected List<Labresource.Software.SoftwareInstall> softwareInstall;

        /**
         * Gets the value of the softwareInstall property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the softwareInstall property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSoftwareInstall().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Labresource.Software.SoftwareInstall }
         * 
         * 
         */
        public List<Labresource.Software.SoftwareInstall> getSoftwareInstall() {
            if (softwareInstall == null) {
                softwareInstall = new ArrayList<Labresource.Software.SoftwareInstall>();
            }
            return this.softwareInstall;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="installLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="executable" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SoftwareInstall {

            @XmlAttribute
            protected String id;
            @XmlAttribute
            protected String type;
            @XmlAttribute
            @XmlSchemaType(name = "anyURI")
            protected String href;
            @XmlAttribute
            protected String name;
            @XmlAttribute
            protected String installLocation;
            @XmlAttribute
            protected String executable;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the installLocation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInstallLocation() {
                return installLocation;
            }

            /**
             * Sets the value of the installLocation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInstallLocation(String value) {
                this.installLocation = value;
            }

            /**
             * Gets the value of the executable property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExecutable() {
                return executable;
            }

            /**
             * Sets the value of the executable property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExecutable(String value) {
                this.executable = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Type {

        @XmlValue
        protected String content;
        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String href;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

    }

}
