//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.13 at 12:00:05 PM BRT 
//


package com.ibm.rqm.xml.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.ibm.rqm.xml.bind.testsuitelog.Suiteelements;
import com.ibm.rqm.xml.bind.testsuitelog.Testplanstateatexecution;
import com.ibm.rqm.xml.bind.testsuitelog.Testsuitestateatexecution;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://jazz.net/xmlns/alm/qm/v0.1/}reportableArtifact">
 *       &lt;sequence>
 *         &lt;element name="webId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}processState"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}title"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}description"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}updated"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}state"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}creator"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}owner"/>
 *         &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}approvals" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}variables"/>
 *         &lt;element name="sequentialExecution" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="passVariables" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="haltOnFailure" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}weight" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}pointspassed" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}pointsfailed" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}pointsattempted" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}pointsblocked" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}pointsinconclusive" minOccurs="0"/>
 *         &lt;element name="pointspermfailed" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="pointsdeferred" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasestotal" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasespassed" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasesfailed" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasesblocked" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasesinconclusive" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasesinprogress" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasesnotstarted" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasesincomplete" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasespartiallyblocked" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcaseserror" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasespermfailed" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasesdeferred" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testcasespaused" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}starttime" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}endtime" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}suiteelements"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}isCurrent" minOccurs="0"/>
 *         &lt;element name="stateid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testcell" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="executionresult" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tasks" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="suiteexecutionrecord">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="testsuite">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="testplan" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="testphase" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="buildrecord" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}customAttributes" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}esignatures" minOccurs="0"/>
 *         &lt;element name="category" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="term" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="termUUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="valueUUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="channel" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testsuitestateatexecution" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/}testplanstateatexecution" minOccurs="0"/>
 *         &lt;element name="configuration" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}markerAny"/>
 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "webId",
    "processState",
    "title",
    "description",
    "updated",
    "state",
    "creator",
    "owner",
    "locked",
    "approvals",
    "variables",
    "sequentialExecution",
    "passVariables",
    "haltOnFailure",
    "weight",
    "pointspassed",
    "pointsfailed",
    "pointsattempted",
    "pointsblocked",
    "pointsinconclusive",
    "pointspermfailed",
    "pointsdeferred",
    "testcasestotal",
    "testcasespassed",
    "testcasesfailed",
    "testcasesblocked",
    "testcasesinconclusive",
    "testcasesinprogress",
    "testcasesnotstarted",
    "testcasesincomplete",
    "testcasespartiallyblocked",
    "testcaseserror",
    "testcasespermfailed",
    "testcasesdeferred",
    "testcasespaused",
    "starttime",
    "endtime",
    "suiteelements",
    "isCurrent",
    "stateid",
    "testcell",
    "executionresult",
    "tasks",
    "suiteexecutionrecord",
    "testsuite",
    "testplan",
    "testphase",
    "buildrecord",
    "customAttributes",
    "esignatures",
    "category",
    "channel",
    "testsuitestateatexecution",
    "testplanstateatexecution",
    "configuration",
    "markerAny",
    "any"
})
@XmlRootElement(name = "testsuitelog")
public class Testsuitelog
    extends ReportableArtifact
{

    protected Integer webId;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    protected ProcessState processState;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected String title;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected String description;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updated;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    protected State state;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected Creator creator;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    protected Owner owner;
    protected Boolean locked;
    protected Approvals approvals;
    @XmlElement(required = true)
    protected Variables variables;
    protected Boolean sequentialExecution;
    protected Boolean passVariables;
    protected Boolean haltOnFailure;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer weight;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer pointspassed;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer pointsfailed;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer pointsattempted;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer pointsblocked;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer pointsinconclusive;
    protected Integer pointspermfailed;
    protected Integer pointsdeferred;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasestotal;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasespassed;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasesfailed;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasesblocked;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasesinconclusive;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasesinprogress;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasesnotstarted;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasesincomplete;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasespartiallyblocked;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcaseserror;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasespermfailed;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasesdeferred;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Integer testcasespaused;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar starttime;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endtime;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/", required = true)
    protected Suiteelements suiteelements;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Boolean isCurrent;
    @XmlElement(required = true)
    protected String stateid;
    protected Testsuitelog.Testcell testcell;
    protected List<Testsuitelog.Executionresult> executionresult;
    protected List<Testsuitelog.Tasks> tasks;
    @XmlElement(required = true)
    protected Testsuitelog.Suiteexecutionrecord suiteexecutionrecord;
    @XmlElement(required = true)
    protected Testsuitelog.Testsuite testsuite;
    protected Testsuitelog.Testplan testplan;
    protected Testsuitelog.Testphase testphase;
    protected Testsuitelog.Buildrecord buildrecord;
    protected CustomAttributes customAttributes;
    protected Esignatures esignatures;
    protected List<Testsuitelog.Category> category;
    protected List<Testsuitelog.Channel> channel;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Testsuitestateatexecution testsuitestateatexecution;
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/tsl/v0.1/")
    protected Testplanstateatexecution testplanstateatexecution;
    protected Testsuitelog.Configuration configuration;
    @XmlElement(required = true)
    protected String markerAny;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the webId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWebId() {
        return webId;
    }

    /**
     * Sets the value of the webId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWebId(Integer value) {
        this.webId = value;
    }

    /**
     * [READ-ONLY] ID or name of the current state of the testsuitelog as seen in the web UI.
     * 
     * @return
     *     possible object is
     *     {@link ProcessState }
     *     
     */
    public ProcessState getProcessState() {
        return processState;
    }

    /**
     * Sets the value of the processState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessState }
     *     
     */
    public void setProcessState(ProcessState value) {
        this.processState = value;
    }

    /**
     * A name given to the testsuitelog.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * [READ-ONLY] An account of the testsuitelog.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * [READ-ONLY] XML dateTime of the last update of the testsuitelog.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdated(XMLGregorianCalendar value) {
        this.updated = value;
    }

    /**
     * An ID or name of the current state of the testsuitelog.
     * 
     * @return
     *     possible object is
     *     {@link State }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link State }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * [IMMUTABLE] The contributor that created the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Creator }
     *     
     */
    public Creator getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Creator }
     *     
     */
    public void setCreator(Creator value) {
        this.creator = value;
    }

    /**
     * The contributor that owns the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Owner }
     *     
     */
    public Owner getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Owner }
     *     
     */
    public void setOwner(Owner value) {
        this.owner = value;
    }

    /**
     * Gets the value of the locked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLocked() {
        return locked;
    }

    /**
     * Sets the value of the locked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocked(Boolean value) {
        this.locked = value;
    }

    /**
     * A collection of approvals that are associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Approvals }
     *     
     */
    public Approvals getApprovals() {
        return approvals;
    }

    /**
     * Sets the value of the approvals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Approvals }
     *     
     */
    public void setApprovals(Approvals value) {
        this.approvals = value;
    }

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link Variables }
     *     
     */
    public Variables getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variables }
     *     
     */
    public void setVariables(Variables value) {
        this.variables = value;
    }

    /**
     * Gets the value of the sequentialExecution property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSequentialExecution() {
        return sequentialExecution;
    }

    /**
     * Sets the value of the sequentialExecution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSequentialExecution(Boolean value) {
        this.sequentialExecution = value;
    }

    /**
     * Gets the value of the passVariables property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPassVariables() {
        return passVariables;
    }

    /**
     * Sets the value of the passVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPassVariables(Boolean value) {
        this.passVariables = value;
    }

    /**
     * Gets the value of the haltOnFailure property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHaltOnFailure() {
        return haltOnFailure;
    }

    /**
     * Sets the value of the haltOnFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHaltOnFailure(Boolean value) {
        this.haltOnFailure = value;
    }

    /**
     * The relative weight of testcase.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeight(Integer value) {
        this.weight = value;
    }

    /**
     * Number of points that passed.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPointspassed() {
        return pointspassed;
    }

    /**
     * Sets the value of the pointspassed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPointspassed(Integer value) {
        this.pointspassed = value;
    }

    /**
     * Number of points that failed.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPointsfailed() {
        return pointsfailed;
    }

    /**
     * Sets the value of the pointsfailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPointsfailed(Integer value) {
        this.pointsfailed = value;
    }

    /**
     * Number of points that were attempted.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPointsattempted() {
        return pointsattempted;
    }

    /**
     * Sets the value of the pointsattempted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPointsattempted(Integer value) {
        this.pointsattempted = value;
    }

    /**
     * Number of points that were blocked.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPointsblocked() {
        return pointsblocked;
    }

    /**
     * Sets the value of the pointsblocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPointsblocked(Integer value) {
        this.pointsblocked = value;
    }

    /**
     * Number of points that were inconclusive.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPointsinconclusive() {
        return pointsinconclusive;
    }

    /**
     * Sets the value of the pointsinconclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPointsinconclusive(Integer value) {
        this.pointsinconclusive = value;
    }

    /**
     * Gets the value of the pointspermfailed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPointspermfailed() {
        return pointspermfailed;
    }

    /**
     * Sets the value of the pointspermfailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPointspermfailed(Integer value) {
        this.pointspermfailed = value;
    }

    /**
     * Gets the value of the pointsdeferred property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPointsdeferred() {
        return pointsdeferred;
    }

    /**
     * Sets the value of the pointsdeferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPointsdeferred(Integer value) {
        this.pointsdeferred = value;
    }

    /**
     * [READ-ONLY] Total number of test cases associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasestotal() {
        return testcasestotal;
    }

    /**
     * Sets the value of the testcasestotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasestotal(Integer value) {
        this.testcasestotal = value;
    }

    /**
     * [READ-ONLY] Number of test cases passed associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasespassed() {
        return testcasespassed;
    }

    /**
     * Sets the value of the testcasespassed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasespassed(Integer value) {
        this.testcasespassed = value;
    }

    /**
     * [READ-ONLY] Number of test cases failed associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasesfailed() {
        return testcasesfailed;
    }

    /**
     * Sets the value of the testcasesfailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasesfailed(Integer value) {
        this.testcasesfailed = value;
    }

    /**
     * [READ-ONLY] Number of test cases blocked associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasesblocked() {
        return testcasesblocked;
    }

    /**
     * Sets the value of the testcasesblocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasesblocked(Integer value) {
        this.testcasesblocked = value;
    }

    /**
     * [READ-ONLY] Number of test cases inconclusive associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasesinconclusive() {
        return testcasesinconclusive;
    }

    /**
     * Sets the value of the testcasesinconclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasesinconclusive(Integer value) {
        this.testcasesinconclusive = value;
    }

    /**
     * [READ-ONLY] Number of test cases in progress associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasesinprogress() {
        return testcasesinprogress;
    }

    /**
     * Sets the value of the testcasesinprogress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasesinprogress(Integer value) {
        this.testcasesinprogress = value;
    }

    /**
     * [READ-ONLY] Number of test cases not started associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasesnotstarted() {
        return testcasesnotstarted;
    }

    /**
     * Sets the value of the testcasesnotstarted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasesnotstarted(Integer value) {
        this.testcasesnotstarted = value;
    }

    /**
     * [READ-ONLY] Number of test cases incomplete associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasesincomplete() {
        return testcasesincomplete;
    }

    /**
     * Sets the value of the testcasesincomplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasesincomplete(Integer value) {
        this.testcasesincomplete = value;
    }

    /**
     * [READ-ONLY] Number of test cases partially blocked associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasespartiallyblocked() {
        return testcasespartiallyblocked;
    }

    /**
     * Sets the value of the testcasespartiallyblocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasespartiallyblocked(Integer value) {
        this.testcasespartiallyblocked = value;
    }

    /**
     * [READ-ONLY] Number of test cases with error associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcaseserror() {
        return testcaseserror;
    }

    /**
     * Sets the value of the testcaseserror property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcaseserror(Integer value) {
        this.testcaseserror = value;
    }

    /**
     * [READ-ONLY] Number of test cases permanently failed associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasespermfailed() {
        return testcasespermfailed;
    }

    /**
     * Sets the value of the testcasespermfailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasespermfailed(Integer value) {
        this.testcasespermfailed = value;
    }

    /**
     * [READ-ONLY] Number of test cases deferred associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasesdeferred() {
        return testcasesdeferred;
    }

    /**
     * Sets the value of the testcasesdeferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasesdeferred(Integer value) {
        this.testcasesdeferred = value;
    }

    /**
     * [READ-ONLY] Number of test cases paused associated with the test suite log.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestcasespaused() {
        return testcasespaused;
    }

    /**
     * Sets the value of the testcasespaused property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestcasespaused(Integer value) {
        this.testcasespaused = value;
    }

    /**
     * XML dateTime when suite execution started.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStarttime() {
        return starttime;
    }

    /**
     * Sets the value of the starttime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStarttime(XMLGregorianCalendar value) {
        this.starttime = value;
    }

    /**
     * XML dateTime when suite execution ended.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndtime() {
        return endtime;
    }

    /**
     * Sets the value of the endtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndtime(XMLGregorianCalendar value) {
        this.endtime = value;
    }

    /**
     * The results individual tests executed by the test suite.
     * 
     * @return
     *     possible object is
     *     {@link Suiteelements }
     *     
     */
    public Suiteelements getSuiteelements() {
        return suiteelements;
    }

    /**
     * Sets the value of the suiteelements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Suiteelements }
     *     
     */
    public void setSuiteelements(Suiteelements value) {
        this.suiteelements = value;
    }

    /**
     * [READ-ONLY] Indicates if this is the most current result at the current time. This is a calculated property, not supported in ETL mode.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCurrent() {
        return isCurrent;
    }

    /**
     * Sets the value of the isCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCurrent(Boolean value) {
        this.isCurrent = value;
    }

    /**
     * Gets the value of the stateid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateid() {
        return stateid;
    }

    /**
     * Sets the value of the stateid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateid(String value) {
        this.stateid = value;
    }

    /**
     * Gets the value of the testcell property.
     * 
     * @return
     *     possible object is
     *     {@link Testsuitelog.Testcell }
     *     
     */
    public Testsuitelog.Testcell getTestcell() {
        return testcell;
    }

    /**
     * Sets the value of the testcell property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testsuitelog.Testcell }
     *     
     */
    public void setTestcell(Testsuitelog.Testcell value) {
        this.testcell = value;
    }

    /**
     * Gets the value of the executionresult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the executionresult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExecutionresult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Testsuitelog.Executionresult }
     * 
     * 
     */
    public List<Testsuitelog.Executionresult> getExecutionresult() {
        if (executionresult == null) {
            executionresult = new ArrayList<Testsuitelog.Executionresult>();
        }
        return this.executionresult;
    }

    /**
     * Gets the value of the tasks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tasks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTasks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Testsuitelog.Tasks }
     * 
     * 
     */
    public List<Testsuitelog.Tasks> getTasks() {
        if (tasks == null) {
            tasks = new ArrayList<Testsuitelog.Tasks>();
        }
        return this.tasks;
    }

    /**
     * Gets the value of the suiteexecutionrecord property.
     * 
     * @return
     *     possible object is
     *     {@link Testsuitelog.Suiteexecutionrecord }
     *     
     */
    public Testsuitelog.Suiteexecutionrecord getSuiteexecutionrecord() {
        return suiteexecutionrecord;
    }

    /**
     * Sets the value of the suiteexecutionrecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testsuitelog.Suiteexecutionrecord }
     *     
     */
    public void setSuiteexecutionrecord(Testsuitelog.Suiteexecutionrecord value) {
        this.suiteexecutionrecord = value;
    }

    /**
     * Gets the value of the testsuite property.
     * 
     * @return
     *     possible object is
     *     {@link Testsuitelog.Testsuite }
     *     
     */
    public Testsuitelog.Testsuite getTestsuite() {
        return testsuite;
    }

    /**
     * Sets the value of the testsuite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testsuitelog.Testsuite }
     *     
     */
    public void setTestsuite(Testsuitelog.Testsuite value) {
        this.testsuite = value;
    }

    /**
     * Gets the value of the testplan property.
     * 
     * @return
     *     possible object is
     *     {@link Testsuitelog.Testplan }
     *     
     */
    public Testsuitelog.Testplan getTestplan() {
        return testplan;
    }

    /**
     * Sets the value of the testplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testsuitelog.Testplan }
     *     
     */
    public void setTestplan(Testsuitelog.Testplan value) {
        this.testplan = value;
    }

    /**
     * Gets the value of the testphase property.
     * 
     * @return
     *     possible object is
     *     {@link Testsuitelog.Testphase }
     *     
     */
    public Testsuitelog.Testphase getTestphase() {
        return testphase;
    }

    /**
     * Sets the value of the testphase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testsuitelog.Testphase }
     *     
     */
    public void setTestphase(Testsuitelog.Testphase value) {
        this.testphase = value;
    }

    /**
     * Gets the value of the buildrecord property.
     * 
     * @return
     *     possible object is
     *     {@link Testsuitelog.Buildrecord }
     *     
     */
    public Testsuitelog.Buildrecord getBuildrecord() {
        return buildrecord;
    }

    /**
     * Sets the value of the buildrecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testsuitelog.Buildrecord }
     *     
     */
    public void setBuildrecord(Testsuitelog.Buildrecord value) {
        this.buildrecord = value;
    }

    /**
     * User defined custom attribute name/value data on this artifact.
     * 
     * @return
     *     possible object is
     *     {@link CustomAttributes }
     *     
     */
    public CustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomAttributes }
     *     
     */
    public void setCustomAttributes(CustomAttributes value) {
        this.customAttributes = value;
    }

    /**
     * Gets the value of the esignatures property.
     * 
     * @return
     *     possible object is
     *     {@link Esignatures }
     *     
     */
    public Esignatures getEsignatures() {
        return esignatures;
    }

    /**
     * Sets the value of the esignatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Esignatures }
     *     
     */
    public void setEsignatures(Esignatures value) {
        this.esignatures = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Testsuitelog.Category }
     * 
     * 
     */
    public List<Testsuitelog.Category> getCategory() {
        if (category == null) {
            category = new ArrayList<Testsuitelog.Category>();
        }
        return this.category;
    }

    /**
     * Gets the value of the channel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Testsuitelog.Channel }
     * 
     * 
     */
    public List<Testsuitelog.Channel> getChannel() {
        if (channel == null) {
            channel = new ArrayList<Testsuitelog.Channel>();
        }
        return this.channel;
    }

    /**
     * [READ-ONLY] Approval state of the associated test suite at the start of execution.
     * 
     * @return
     *     possible object is
     *     {@link Testsuitestateatexecution }
     *     
     */
    public Testsuitestateatexecution getTestsuitestateatexecution() {
        return testsuitestateatexecution;
    }

    /**
     * Sets the value of the testsuitestateatexecution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testsuitestateatexecution }
     *     
     */
    public void setTestsuitestateatexecution(Testsuitestateatexecution value) {
        this.testsuitestateatexecution = value;
    }

    /**
     * [READ-ONLY] Approval state of the associated test plan at the start of execution.
     * 
     * @return
     *     possible object is
     *     {@link Testplanstateatexecution }
     *     
     */
    public Testplanstateatexecution getTestplanstateatexecution() {
        return testplanstateatexecution;
    }

    /**
     * Sets the value of the testplanstateatexecution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testplanstateatexecution }
     *     
     */
    public void setTestplanstateatexecution(Testplanstateatexecution value) {
        this.testplanstateatexecution = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Testsuitelog.Configuration }
     *     
     */
    public Testsuitelog.Configuration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testsuitelog.Configuration }
     *     
     */
    public void setConfiguration(Testsuitelog.Configuration value) {
        this.configuration = value;
    }

    /**
     * [READ-ONLY] A empty marker.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkerAny() {
        return markerAny;
    }

    /**
     * Sets the value of the markerAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkerAny(String value) {
        this.markerAny = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Buildrecord {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the build record.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="term" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="termUUID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="valueUUID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Category {

        @XmlAttribute
        protected String term;
        @XmlAttribute
        protected String value;
        @XmlAttribute
        protected String termUUID;
        @XmlAttribute
        protected String valueUUID;

        /**
         * Gets the value of the term property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTerm() {
            return term;
        }

        /**
         * Sets the value of the term property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTerm(String value) {
            this.term = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the termUUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTermUUID() {
            return termUUID;
        }

        /**
         * Sets the value of the termUUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTermUUID(String value) {
            this.termUUID = value;
        }

        /**
         * Gets the value of the valueUUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValueUUID() {
            return valueUUID;
        }

        /**
         * Sets the value of the valueUUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValueUUID(String value) {
            this.valueUUID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Channel {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the channel
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Configuration {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Executionresult {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the executionresult.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Suiteexecutionrecord {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the suite execution record.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Tasks {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the task.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Testcell {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the testcell.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Testphase {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the phase.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Testplan {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the test plan.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Testsuite {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * [READ-ONLY] UUID of the test suite.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
